parameters:
  # the following parameters enable Ceph backends for Cinder, Glance, and Nova
  CephClientUserName: openstack
  NovaEnableRbdBackend: true
  CinderEnableRbdBackend: true
  GlanceBackend: rbd
  NovaRbdPoolName: vms
  CinderRbdPoolName: volumes
  GlanceRbdPoolName: images

  # finally we disable the Cinder LVM backend
  CinderEnableIscsiBackend: false
