heat_template_version: 2014-10-16

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: repo_config}

  repo_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        if [[ $(hostname) == *controller* ]]; then
            echo 2 > /proc/sys/net/ipv4/conf/default/rp_filter
            echo 2 > /proc/sys/net/ipv4/conf/all/rp_filter
            echo "net.ipv4.conf.default.rp_filter = 2" >> /etc/sysctl.conf
        fi

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
