- name: fetch undercloud VM IP address
  shell: grep $(tripleo get-vm-mac instack) /var/lib/libvirt/dnsmasq/default.leases| awk '{print $3;}' | uniq
  sudo_user: stack
  sudo: yes
  changed_when: false
  register: undercloud_ip

- name: set undercloud_ip fact
  set_fact:
    undercloud_ip: "{{ undercloud_ip.stdout }}"

- name: assert that undercloud_ip is not empty
  shell: echo "Something went wrong - cannot fetch undercloud VM's IP address. Check /tmp/instack-virt-setup.out."; false
  when: not undercloud_ip
