---
vpn: yes

instack:
 destroy: no
 undercloud_node:
   vcpus: 8
   memory: 16384
 overcloud_nodes: 
   number: 15
   vcpus: 4
   memory: 16384

undercloud:
  install: yes

overcloud:
  install: yes
  controller: 1
  compute: 1
  ceph: 0
  cinder: 0
  swift:  0
  images_build: no
  images_location: "https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/"
