---
- name: Register nodes
  shell: source /home/stack/stackrc; openstack baremetal import --json instackenv.json
  register: nodes_reg

- name: Assign kernel and ramdisk
  shell: source /home/stack/stackrc; openstack baremetal configure boot

- name: Introspect nodes
  shell: source /home/stack/stackrc; openstack baremetal introspection bulk start
  register: nodes_intro

- name: Nodes introspection status
  debug:
    msg: "{{ nodes_intro.stdout }}"

- name: Create flavors
  shell: source /home/stack/stackrc; openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 baremetal; openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" baremetal
  register: flavors_reg

- name: Flavors registration status
  debug:
    msg: "{{ flavors_reg.stdout }}"
