---
- name: enable epel when distro is not Fedora
  command: rpm -ivh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  ignore_errors: yes
  when: ansible_distribution != "Fedora"

- name: install openvpn
  yum: name=openvpn state=installed

- name: Fetch ca.crt
  command: scp -o 'StrictHostKeyChecking=no' root@{{ hostvars['physical_host']['ansible_default_ipv4']['address'] }}:/etc/openvpn/keys/ca.crt /etc/openvpn/stack-server-ca.crt

- name: Fetch stack.key
  command: scp -o 'StrictHostKeyChecking=no' root@{{ hostvars['physical_host']['ansible_default_ipv4']['address'] }}:/etc/openvpn/keys/stack.key /etc/openvpn/stack-server-stack.key

- name: Fetch stack.crt
  command: scp -o 'StrictHostKeyChecking=no' root@{{ hostvars['physical_host']['ansible_default_ipv4']['address'] }}:/etc/openvpn/keys/stack.crt /etc/openvpn/stack-server-stack.crt

- name: Create config file
  template: src=stack.conf.j2 dest=/etc/openvpn/stack.conf

- name: Symlink openvpn service
  file: src=/lib/systemd/system/openvpn\@.service dest=/etc/systemd/system/multi-user.target.wants/openvpn\@stack.service state=link

- name: enable openvpn
  service: name=openvpn@stack.service state=restarted enabled=yes
