---
- name: Build overcloud images
  environment: 
    USE_DELOREAN_TRUNK: 1
    DELOREAN_TRUNK_REPO: "http://trunk.rdoproject.org/liberty/centos7/current-passed-ci/"
    DELOREAN_REPO_FILE: "delorean.repo"
  shell: openstack overcloud image build --all

- name: Load images to Glance
  shell: source /home/stack/stackrc; openstack overcloud image upload
